DROP DATABASE IF EXISTS ales_DB;
CREATE database ales_DB;

USE ales_DB;

CREATE TABLE aleslist (
  BEERS VARCHAR(255) DEFAULT NULL,
  WINE VARCHAR(255) DEFAULT NULL,
  LIQUOR VARCHAR(255) DEFAULT NULL,

  
);

SELECT * FROM aleslist;
