DROP DATABASE IF EXISTS tales_DB;
CREATE database tales_DB;

USE tales_DB;

CREATE TABLE taleslist (
  ASIN VARCHAR(10) DEFAULT NULL,
  FILE_NAME VARCHAR(14) DEFAULT NULL,
  IMAGE_URL VARCHAR(59) DEFAULT NULL,
  TITLE VARCHAR(500) DEFAULT NULL,
  AUTHOR VARCHAR(260) DEFAULT NULL,
  CATEGORY_ID INT(2) DEFAULT NULL,
  CATEGORY VARCHAR(30) DEFAULT NULL
  
);

SELECT * FROM taleslist;
